# config.py
# Language and database configurations

LANGUAGES = {
    "en": {
        "title": "📡 IoT Data Management & Visualization",
        "sidebar_header": "🎛️ Data Generation Settings",
        "truncate_button": "🗑️ Clear Device Data Table",
        "truncate_confirm": "Are you sure you want to clear all data in the device_data table? This action cannot be "
                            "undone.",
        "confirm_clear_button": "✅ Confirm",
        "cancel_clear_button": "❌ Cancel",
        "truncate_success": "✅ Device data table cleared successfully",
        "truncate_error": "❌ Failed to clear device data table: {error}",
        "filename_label": "Filename Prefix",
        "record_count_label": "Record Count",
        "storage_path_label": "Storage Path",
        "save_format_label": "Save Format",
        "preview_count_label": "Preview Count",
        "force_gps_label": "Include GPS",
        "force_accelerometer_label": "Include Accelerometer",
        "battery_miss_rate_label": "Battery Missing Rate",
        "pressure_miss_rate_label": "Pressure Missing Rate",
        "with_notes_label": "Include Notes Field",
        "tab1_title": "📦 Generate, Save & Insert",
        "tab2_title": "🔍 Basic Query",
        "tab3_title": "🗺️ Spatial Query",
        "generate_sub": "📦 Data Generation & Management",
        "generate_subheader": "🔢 Data Generation",
        "generate_button": "🚀 Generate Data",
        "generating": "Generating...",
        "generate_success": "✅ Generated {count} records",
        "save_success": "📁 Saved to: {path}",
        "data_preview": "👀 Data Preview",
        "insert_spatial_subheader": "🔂 Insert & Spatial Operations",
        "insert_info": "Found {count} generated records ready for insertion.",
        "insert_warning": "No generated data available. Generate data first.",
        "insert_button": "🚀 Insert Generated Data",
        "inserting": "Inserting...",
        "init_spatial_button": "🗺️ Initialize Spatial",
        "init_spatial": "Initializing spatial extension...",
        "update_geometry_button": "🔄 Update Geometry",
        "update_geometry": "Updating geometry...",
        "init_spatial_success": "✅ Spatial extension and geom column initialized",
        "init_spatial_error": "❌ Failed to initialize spatial extension: {error}",
        "update_geometry_success": "✅ Updated geometry for {count} records",
        "update_geometry_warning": "No records updated",
        "update_geometry_error": "❌ Failed to update geometry: {error}",
        "insert_success": "✅ Inserted {success} records, skipped {skip}, took {elapsed:.2f}s",
        "insert_error": "❌ Insertion failed",
        "query_subheader": "🔎 Query Parameters",
        "min_temp_label": "Min Temperature",
        "max_temp_label": "Max Temperature",
        "min_battery_label": "Min Battery",
        "status_label": "Device Status",
        "region_label": "Region Keyword",
        "page_label": "Page Number",
        "query_button": "🔍 Query",
        "query_all_button": "🌐 Query All",
        "querying": "Querying...",
        "querying_all": "Querying all data...",
        "query_results_subheader": "📊 Query Results",
        "query_success": "✅ Query successful, {count} records, took {time:.2f}s",
        "query_warning": "⚠️ No matching data found",
        "query_all_warning": "⚠️ No data found",
        "query_error": "❌ Query failed: {error}",
        "download_csv": "📥 Download CSV",
        "query_info": "Please perform a query first",
        "spatial_subheader": "🔍 Spatial Query Parameters",
        "lon_label": "Center Longitude",
        "lat_label": "Center Latitude",
        "radius_label": "Query Radius (km)",
        "point_scale_label": "Point Size Scale",
        "nearby_button": "🚀 Query Nearby",
        "all_devices_button": "🌐 All Devices",
        "querying_nearby": "Querying devices...",
        "querying_all_devices": "Loading all device data...",
        "spatial_results_subheader": "📊 Spatial Results",
        "nearby_results": "📡 Devices within {radius} km",
        "all_devices_results": "📡 All Devices",
        "nearby_success": "✅ Found {count} devices",
        "all_devices_success": "✅ Loaded {count} devices",
        "nearby_warning": "❗ No nearby devices found",
        "all_devices_warning": "❗ No device data found",
        "map_warning": "⚠️ Data empty, cannot draw map.",
        "language_label": "Language",
        "device_id": "Device ID",
        "status": "Status",
        "battery": "Battery"
    },
    "zh": {
        "title": "📡 物联网数据管理与可视化",
        "sidebar_header": "🎛️ 数据生成设置",
        "truncate_button": "🗑️ 清除设备数据表",
        "truncate_confirm": "您确定要清除设备数据表中的所有数据吗？此操作无法撤销。",
        "confirm_clear_button": "✅ 确认",
        "cancel_clear_button": "❌ 取消",
        "truncate_success": "✅ 设备数据表已成功清除",
        "truncate_error": "❌ 清除设备数据表失败：{error}",
        "filename_label": "文件名前缀",
        "record_count_label": "记录数量",
        "storage_path_label": "存储路径",
        "save_format_label": "保存格式",
        "preview_count_label": "预览数量",
        "force_gps_label": "包含GPS",
        "force_accelerometer_label": "包含加速度计",
        "battery_miss_rate_label": "电池缺失率",
        "pressure_miss_rate_label": "压力缺失率",
        "with_notes_label": "包含备注字段",
        "tab1_title": "📦 生成、保存与插入",
        "tab2_title": "🔍 基础查询",
        "tab3_title": "🗺️ 空间查询",
        "generate_sub": "📦 数据生成与管理",
        "generate_subheader": "🔢 数据生成",
        "generate_button": "🚀 生成数据",
        "generating": "生成中...",
        "generate_success": "✅ 已生成 {count} 条记录",
        "save_success": "📁 已保存至：{path}",
        "data_preview": "👀 数据预览",
        "insert_spatial_subheader": "🔂 插入与空间操作",
        "insert_info": "找到 {count} 条生成记录准备插入。",
        "insert_warning": "没有生成的数据。请先生成数据。",
        "insert_button": "🚀 插入生成数据",
        "inserting": "插入中...",
        "init_spatial_button": "🗺️ 配置PostGIS拓展",
        "init_spatial": "正在配置PostGIS扩展...",
        "update_geometry_button": "🔄 更新gemo空间列",
        "update_geometry": "正在更新gemo空间列...",
        "init_spatial_success": "✅ PostGIS扩展和gemo空间列已初始化",
        "init_spatial_error": "❌ 初始化空间扩展失败：{error}",
        "update_geometry_success": "✅ 为 {count} 条记录更新了gemo列",
        "update_geometry_warning": "没有记录被更新",
        "update_geometry_error": "❌ 更新gemo列失败：{error}",
        "insert_success": "✅ 插入 {success} 条记录，跳过 {skip} 条，耗时 {elapsed:.2f}秒",
        "insert_error": "❌ 插入失败",
        "query_subheader": "🔎 查询参数",
        "min_temp_label": "最低温度",
        "max_temp_label": "最高温度",
        "min_battery_label": "最低电量",
        "status_label": "设备状态",
        "region_label": "区域关键字",
        "page_label": "页码",
        "query_button": "🔍 查询",
        "query_all_button": "🌐 查询全部",
        "querying": "查询中...",
        "querying_all": "查询全部数据中...",
        "query_results_subheader": "📊 查询结果",
        "query_success": "✅ 查询成功，{count} 条记录，耗时 {time:.2f}秒",
        "query_warning": "⚠️ 没有找到匹配的数据",
        "query_all_warning": "⚠️ 没有找到数据",
        "query_error": "❌ 查询失败：{error}",
        "download_csv": "📥 下载CSV",
        "query_info": "请先执行查询",
        "spatial_subheader": "🔍 空间查询参数",
        "lon_label": "中心经度",
        "lat_label": "中心纬度",
        "radius_label": "查询半径（公里）",
        "point_scale_label": "点大小比例",
        "nearby_button": "🚀 查询附近",
        "all_devices_button": "🌐 全部设备",
        "querying_nearby": "正在查询设备...",
        "querying_all_devices": "正在加载所有设备数据...",
        "spatial_results_subheader": "📊 空间查询结果",
        "nearby_results": "📡 {radius} 公里内的设备",
        "all_devices_results": "📡 全部设备",
        "nearby_success": "✅ 找到 {count} 台设备",
        "all_devices_success": "✅ 加载 {count} 台设备",
        "nearby_warning": "❗ 未找到附近设备",
        "all_devices_warning": "❗ 没有设备数据",
        "map_warning": "⚠️ 数据为空，无法绘制地图。",
        "language_label": "语言",
        "device_id": "设备ID",
        "status": "状态",
        "battery": "电量"
    }
}

DB_CONFIG = {
    "dbname": "iot_data",
    "user": "postgres",
    "password": "Asd123.456",
    "host": "localhost",
    "port": "5432",
    "connect_timeout": 5
}
